import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GoogleLogin } from "@react-oauth/google";
import { useGoogleOneTapLogin } from "@react-oauth/google";
import { googleLogout } from '@react-oauth/google';


// const login = useGoogleOneTapLogin({
//   onSuccess: credentialResponse => {
//     console.log(credentialResponse);
//   },
//   onError: () => {
//     console.log('Login Failed');
//   },
// });
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
        <header>
          FamWallet
        </header>
				<GoogleLogin
					onSuccess={(credentialResponse) => {
						console.log(credentialResponse);
					}}
					onError={() => {
						console.log("Login Failed");
					}}
				/>
				;
			</main>
		</>
	);
}
